---

- hosts: "k8s"
  gather_facts: false
  roles:
    - "defunctzombie.coreos-bootstrap"

  tasks:

    - template:
        src: "templates/rules-save.j2"
        dest: "/var/lib/iptables/rules-save"
      sudo: true

    - service:
        name: "iptables-restore"
        state: "restarted"
        enabled: true
      sudo: true

    - command: "docker login -e '{{item.email}}' -u '{{item.username}}' -p '{{item.password}}' '{{item.host}}'"
      with_items: "{{docker_repos}}"

    - synchronize:
        src: "ssl-certs/"
        dest: "/home/core/ssl-certs"
        delete: true
