---

- hosts: "k8s"
  gather_facts: false
  roles:
    - "defunctzombie.coreos-bootstrap"

  tasks:

    - template:
        src: "templates/rules-save.j2"
        dest: "/var/lib/iptables/rules-save"
      sudo: true

    - command: "docker login -e '{{item.email}}' -u '{{item.username}}' -p '{{item.password}}' '{{item.host}}'"
      with_items: "{{docker_repos}}"

    - file:
        src: "/home/core/.docker"
        dest: "/root/.docker"
        state: "link"
      sudo: true

    - synchronize:
        src: "ssl-certs/"
        dest: "/home/core/ssl-certs"
        delete: true

- hosts: "node"
  gather_facts: false
  tasks:

  - lineinfile:
      state: "present"
      dest: "/etc/vulcand-env"
      line: "VULCAND_SEAL_KEY={{vulcand_secret}}"
      create: "yes"
    sudo: true
