---

- hosts: "k8s"
  gather_facts: false
  roles:
    - "defunctzombie.coreos-bootstrap"

  tasks:

  - template:
      src: "templates/rules-save.j2"
      dest: "/var/lib/iptables/rules-save"
    sudo: true
    register: "iptables_rules"

  - service:
      name: "iptables-restore"
      state: "restarted"
      enabled: true
    sudo: true
    when: "iptables_rules|changed"

  - service:
      name: "docker"
      state: "restarted"
    sudo: true
    when: "iptables_rules|changed"
    ignore_errors: true

- hosts: "node"
  gather_facts: false
  tasks:

  - synchronize:
      src: "ssl/"
      dest: "/home/core/ssl/"
    sudo: true
