---

- hosts: "localhost"
  vars:
    ansible_connection: "local"
    ansible_python_interpreter: "python"
  tasks:

    - set_fact:
        master_host: "{{hostvars[groups['master'][0]]}}"

    - template:
        src: "templates/dns-rc.yaml.j2"
        dest: "tmp/dns-rc.yaml"

    - command: "kubectl create -f templates/kube-system-namespace.yaml"
      ignore_errors: true
    - command: "kubectl create -f tmp/dns-rc.yaml"
    - command: "kubectl create -f templates/dns-svc.yaml"
