---

- hosts: "localhost"
  vars:
    ansible_connection: "local"
    ansible_python_interpreter: "python"
  tasks:

    - command: "kubectl create -f tmp/dns-rc.yaml"
    - command: "kubectl create -f templates/dns-svc.yaml"
