---

- hosts: "localhost"
  vars:
    ansible_connection: "local"
    ansible_python_interpreter: "python"
  tasks:

    - set_fact:
        master_host: "{{hostvars[groups['master'][0]]}}"

    - template:
        src: "templates/dns-controller.yaml.j2"
        dest: "/tmp/dns-controller.yaml"

    - command: >
      kubelet create -f /tmp/dns-controller.yaml

    - command: >
      kubelet create -f templates/dns-service.yaml
