kind: "ReplicationController"
apiVersion: "v1beta3"
metadata:
  name: "percona-galera"
  labels:
    name: "percona-galera"
spec:
  replicas: 3
  selector:
    name: "percona-galera"
  template:
    metadata:
      labels:
        name: "percona-galera"
    spec:
      containers:
        - name: "etcd"
          image: "arisechurch/etcd:v2.0.10"
          command:
            - "bash"
            - "-c"
            - >-
              hostip=$(hostname -i)

              /usr/local/etcd/etcd
              --name $hostip
              --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
              --listen-peer-urls=http://0.0.0.0:2380,http://0.0.0.0:7001
              --advertise-client-urls=http://$hostip:2379,http://$hostip:4001
              --initial-advertise-peer-urls=http://$hostip:2380,http://$hostip:7001
              --discovery={{discovery}}
          ports:
            - containerPort: 4001
              protocol: "TCP"
            - containerPort: 7001
              protocol: "TCP"
        - name: "percona-galera"
          image: "paulczar/percona-galera"
          command:
            - "bash"
            - "-c"
            - >-
              HOST=$(hostname -i)
              CLUSTER=galera
              PUBLISH=3306
              /app/bin/boot
          ports:
            - containerPort: 3306
              protocol: "TCP"
            - containerPort: 4444
              protocol: "TCP"
            - containerPort: 4567
              protocol: "TCP"
            - containerPort: 4568
              protocol: "TCP"
